Added native browser console app
raphaellondner-okta/okta-oauth-nativewindows pull request #2
Opened 2016-12-14 22:09 UTC by raphaellondner-okta

Leverages the default browser (and leveraging any existing Okta browser session) for authentication and OAuth authorization (using Authorization Code Flow w/ PKCE)

2017-01-04 00:50 UTC, raphaellondner-okta commented
@marksztainbok-okta Hope you had a good holiday break! Is there any way you could review and approve this PR this week? Thank you :)

2017-01-05 18:23 UTC, yiyangli-okta commented on Okta.Samples.OpenIDConnect.Console/KeyGenerator.cs
> +            char[] chars = new char[62];
`char[] chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890".ToCharArray();` is good enough.

2017-01-05 18:55 UTC, yiyangli-okta requested changes

2017-01-05 18:55 UTC, yiyangli-okta commented on Okta.Samples.OpenIDConnect.Console/KeyGenerator.cs
> +            byte[] data = new byte[1];
`data` is initialized but later initialized with size of `maxSize`

2017-01-05 18:55 UTC, yiyangli-okta commented on Okta.Samples.OpenIDConnect.Console/KeyGenerator.cs
> +            foreach (byte b in data)
if removing the initializing on line 16 will give you a warning on 24, you could put the iteration within `using` block

2017-01-05 18:55 UTC, yiyangli-okta commented on Okta.Samples.OpenIDConnect.Console/Program.cs
> +                foreach (Claim c in form.oAuthWebBrowser1.IDClaims)
missing `{}`

2017-01-05 18:55 UTC, yiyangli-okta commented on Okta.Samples.OpenIDConnect.Console/Program.cs
> +        private static void ValidateToken(string jwtToken)
empty method?

2017-01-05 18:55 UTC, yiyangli-okta commented on Okta.Samples.OpenIDConnect.NativeBrowserConsole/Program.cs
> +
extra lines?

2017-01-05 18:55 UTC, yiyangli-okta commented on Okta.Samples.OpenIDConnect.NativeBrowserConsole/Program.cs
> +            string base64 = Convert.ToBase64String(buffer);
```
return Convert.ToBase64String(buffer)
            .Replace("+", "-")
            .Replace("/", "_")
            .Replace("=", "");
```

2017-01-05 18:55 UTC, yiyangli-okta commented on Okta.Samples.OpenIDConnect.NativeBrowserConsole/Program.cs
> +                string strEx = ex.ToString();
any usage for `strEx`?

2017-01-05 18:55 UTC, yiyangli-okta commented on Okta.Samples.OpenIDConnect.NativeBrowserConsole/Program.cs
> +            string json = string.Empty;
nit: put 252 behind 246 and also use `var`

2017-01-05 18:55 UTC, yiyangli-okta commented on Okta.Samples.OpenIDConnect.NativeBrowserConsole/Program.cs
> +            if(_authZConfig!=null)
space between `if` and `(`

2017-01-05 18:55 UTC, yiyangli-okta commented on Okta.Samples.OpenIDConnect.NativeBrowserConsole/Program.cs
> +            if(_authZConfig!=null)
space between `if` and `(`

2017-01-05 18:55 UTC, yiyangli-okta commented on Okta.Samples.OpenIDConnect.Console/Okta OpenID Connect Console (Implicit Flow - Embedded Browser).csproj
> +      <HintPath>..\packages\IdentityModel.2.1.1\lib\net45\IdentityModel.dll</HintPath>
did you forget to put nuget package config? I didn't see the dll file in the repo.

2017-01-05 19:32 UTC, raphaellondner-okta commented on Okta.Samples.OpenIDConnect.Console/KeyGenerator.cs
> +            byte[] data = new byte[1];
Fixed with `byte[] data  = null;`

2017-01-05 19:34 UTC, raphaellondner-okta commented on Okta.Samples.OpenIDConnect.Console/Program.cs
> +                foreach (Claim c in form.oAuthWebBrowser1.IDClaims)
Not sure what the issue is, I've checked this piece of code works

2017-01-05 19:35 UTC, raphaellondner-okta commented on Okta.Samples.OpenIDConnect.Console/Program.cs
> +        private static void ValidateToken(string jwtToken)
removed

2017-01-05 19:39 UTC, yiyangli-okta commented on Okta.Samples.OpenIDConnect.Console/Program.cs
> +                foreach (Claim c in form.oAuthWebBrowser1.IDClaims)
nothing wrong except the style, use a `{}` between and after an iteration body

2017-01-05 19:46 UTC, raphaellondner-okta commented on Okta.Samples.OpenIDConnect.Console/Okta OpenID Connect Console (Implicit Flow - Embedded Browser).csproj
> +      <HintPath>..\packages\IdentityModel.2.1.1\lib\net45\IdentityModel.dll</HintPath>
The package file is here --> https://github.com/raphaellondner-okta/okta-oauth-nativewindows/blob/google-console/Okta.Samples.OpenIDConnect.Console/packages.config

2017-01-05 19:47 UTC, yiyangli-okta commented on Okta.Samples.OpenIDConnect.Console/Okta OpenID Connect Console (Implicit Flow - Embedded Browser).csproj
> +      <HintPath>..\packages\IdentityModel.2.1.1\lib\net45\IdentityModel.dll</HintPath>
my bad, did see it.

2017-01-05 19:56 UTC, raphaellondner-okta commented on Okta.Samples.OpenIDConnect.Console/Program.cs
> +                foreach (Claim c in form.oAuthWebBrowser1.IDClaims)
got it :)

2017-01-05 20:01 UTC, raphaellondner-okta commented
@yiyangli-okta thanks for the quick review and feedback! Can take a peek at my latest [commit](https://github.com/raphaellondner-okta/okta-oauth-nativewindows/pull/2/commits/bca020962002742aa9ef317b4efd04c07ef1f164) based on your feedback?

2017-01-05 20:02 UTC, yiyangli-okta commented
lgtm, please rebased 🚢

2017-01-05 20:02 UTC, yiyangli-okta approved these changes

2017-01-06 17:20 UTC, merged